before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/checkson-io/checkson-cli/cmd.Version={{.Tag}} -X github.com/checkson-io/checkson-cli/cmd.GitCommit={{.ShortCommit}} -X github.com/checkson-io/checkson-cli/cmd.BuildTime={{.Date}}
    binary: checkson
    goos:
      - darwin
      - linux
      - windows
#    hooks:
#      post: './generate_completion.sh {{ .Target }} {{ .Path }}'

archives:
  - id: default
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
nfpms:
  - id: default
    homepage: https://checkson.io/
    maintainer: Stefan Hudelmaier <[stefan@huditech.com]>
    description: A command-line interface for interaction with Checkson
    license: Apache 2.0

    formats:
      - deb
      - rpm

release:
  disable: false
  draft: false

snapcrafts:
  - id: default
    publish: true
    summary: A command-line interface for interaction with checkson.io
    description: |
      A CLI for interacting with https://checkson.io
    grade: stable
    confinement: strict
    license: Apache-2.0
    apps:
      checkson:
        plugs: ["home", "network"]
        completer: checkson-completion.bash

#brews:
#  -
#    tap:
#      owner: checkson-io
#      name: homebrew-packages
#
#    commit_author:
#      name: goreleaserbot
#      email: goreleaser@checkson-io
#
#    folder: Formula
#
#    homepage: https://checkson.io
#
#    description: |
#      A command-line interface for interaction with checkson.io
#
#    skip_upload: false
#
#dockers:
#  -
#    skip_push: false
#    dockerfile: Dockerfile.Ubuntu
#    binaries:
#      - checkson
#    image_templates:
#      - "checkson/checkson:latest-ubuntu"
#      - "checkson/checkson:{{ .Tag }}-ubuntu"
#      - "checkson/checkson:latest"
#      - "checkson/checkson:{{ .Tag }}"
#  -
#    skip_push: false
#    dockerfile: Dockerfile.Scratch
#    binaries:
#      - checkson
#    image_templates:
#      - "checkson/checkson:latest-scratch"
#      - "checkson/checkson:{{ .Tag }}-scratch"
