name: release

#on:
#  push:
#    tags:
#      - v*
on: push

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      # -
      #  name: Snapcraft login
      #  uses: samuelmeuli/action-snapcraft@v1
      #  with:
      #    # snapcraft export-login --snaps checkson --channels stable -
      #    snapcraft_token: ${{ secrets.snapcraft_token }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --debug
        env:
          # create personal access token: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
