name: release

on:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      # snapcraft export-login --snaps checkson --channels stable -
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17

      -
        name: Snapcraft login
        uses: samuelmeuli/action-snapcraft@v2

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --debug
        env:
          # create personal access token: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
